export const FEATURED_PRODUCT_REQUEST = "FEATURED_PRODUCT_REQUEST";
export const FEATURED_PRODUCT_SUCCESS = "FEATURED_PRODUCT_SUCCESS";
export const FEATURED_PRODUCT_FAIL = "FEATURED_PRODUCT_FAIL";

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";

export const NEW_ARRIVAL_PRODUCT_REQUEST = "NEW_ARRIVAL_PRODUCT_REQUEST";
export const NEW_ARRIVAL_PRODUCT_SUCCESS = "NEW_ARRIVAL_PRODUCT_SUCCESS";
export const NEW_ARRIVAL_PRODUCT_FAIL = "NEW_ARRIVAL_PRODUCT_FAIL";

export const HOT_PRODUCT_REQUEST = "HOT_PRODUCT_REQUEST";
export const HOT_PRODUCT_SUCCESS = "HOT_PRODUCT_SUCCESS";
export const HOT_PRODUCT_FAIL = "HOT_PRODUCT_FAIL";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
